name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build, and test
        run: |
          npm install -g yarn
          yarn
          docker pull postgres:9.6.19-alpine
          docker pull testcontainers/ryuk:0.3.0
          yarn type-check
          yarn test
        env:
          CI: "true"
